/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cidemo

class App {
    val greeting: String
        get() {
            return "Hello World with CI!"
        }

    fun getNumOfActors() : Int{
        UtilsInKotlin.loadRules()
        UtilsInKotlin.showSystemConfiguration()
        val v = UtilsInKotlin.getActorNumber()
        println("App v=$v")
        return v
    }
}

fun main(args: Array<String>) {
    println(App().greeting)
    println(  "numOfActors = ${App().getNumOfActors()}")
}
