/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cidemo

class App {
    val greeting: String
        get() {
            return "Hello World with CI!"
        }

    fun getNumOfActors() : Int{
        UtilsInKotlin.loadRules()
        //UtilsInKotlin.showSystemConfiguration()
        val numOfActors = UtilsInKotlin.getActorNumber()
        println("App numOfActors=$numOfActors")
        return numOfActors
    }
}

fun main(args: Array<String>) {
    val app = App()
    println(app.greeting)
    println(  "numOfActors = ${app.getNumOfActors()}")
}
