# This is a basic workflow to help you get started with Actions

name: CIdemoStart

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest          # downloads a copy of your repository on the runner

    steps:
      - uses: actions/checkout@v2   #downloads a copy of your repository on the runner
      - name: Set up JDK 1.8        #configures the Java 1.8 JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: echo Attempt to build
      - name: Change wrapper permissions
        run: chmod +x ./gradlew     #to gain gradlew run permission        
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build
        run: ./gradlew build  
        #runs the gradlew wrapper script to ensure that your code builds, tests pass, and a package can be created
      - uses: actions/upload-artifact@v2
        with:
          #name: Package
          #path: app/build/libs
          name: AppDistribution
          path: app/build/distributions/*.tar
      - name: Build and Push Docker Image
        uses:mr-smithers-excellent
        with:
          image: nanajanashia/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
